### ISSUE TITLE
Settings Format

### ISSUE THREAD

**Issue by OnegaiOsu** [thebetioplane/OsuReplayViewer#2]
Do I erase the (#) ?  Will I still write the file name ? please send examples of the correct format for the settings file

**Comment by thebetioplane** [comment]
The file that gets created when you don't have a settings file is a sample format.
```
# Lines starting with a # are ignored
# Do not change the order of the settings

# Path to osu!.db
C:\osu!\osu!.db

# Path to your osu! song folder
C:\osu!\songs\

# Path to a replay folder
C:\osu!\replays\
```
The sample demonstrates a "normal" install of your osu in C:\osu!\, "normal" meaning that the song folder and replay folder names are the default. If your osu was installed in C:\Program Files\osu!, then your config file could look like:
```
C:\Program Files\osu!\osu!.db
C:\Program Files\osu!\songs\
C:\Program Files\osu!\replays\
```
The # are just comments, they are just extra information that get ignored when your settings.txt is loaded and can be omitted or left in.

**Comment by OnegaiOsu** [comment]
My config looks like that but my .db file has a different name. I tried erasing the comments but the app still cant read the locations. Attached is my osu folder and my settings file
![screenshot 36](https://user-images.githubusercontent.com/47490023/52529052-db6e7580-2d25-11e9-84ae-92d4fdd1440f.png)

![screenshot 38](https://user-images.githubusercontent.com/47490023/52529098-c3e3bc80-2d26-11e9-8286-697702ffce46.png)
 edit: wrong screenshot but still reports that the locations are invalid

**Comment by thebetioplane** [comment]
Well your osu is not in `C:\Program Files\`, it's in `C:\Users\Admin\AppData\Local\`.
Write your config to reflect that:
```
C:\Users\Admin\AppData\Local\osu!\osu!.db.636797130591221452
C:\Users\Admin\AppData\Local\osu!\Songs\
C:\Users\Admin\AppData\Local\osu!\Replays\
```

**Comment by OnegaiOsu** [comment]
Sorry for the inconvenience but please check the edit

**Comment by OnegaiOsu** [comment]
ohh i forgot the local owooo

**Comment by OnegaiOsu** [comment]
Quick Load works, but cant read osu.db @thebetioplane

**Comment by thebetioplane** [comment]
Delete your osu!.db and let osu! remake it for you, it's probably outdated.

**Comment by OnegaiOsu** [comment]
Problem fixed. Thanks @thebetioplane
