### ISSUE TITLE
Neglected app, so it crashes

### ISSUE THREAD

**Issue by PF94** [thebetioplane/OsuReplayViewer#3]
great app :clap: :clap: :clap:

**Comment by thebetioplane** [comment]
probably needs you to install XNA framework (undocumented depedency)
https://www.microsoft.com/en-us/download/details.aspx?id=20914
unless you are getting a message box telling you of a different problem

**Comment by PF94** [comment]
when launching the app, it closes. i remember moving my entire osu folder

**Comment by PF94** [comment]
nm i installed xna framework and it works. it isn't neglected despite the last commit being released in 2016!
