### ISSUE TITLE
osu!.db doesn't load anymore

### ISSUE THREAD

**Issue by obrigadex** [thebetioplane/OsuReplayViewer#5]
today (07/11/2019, DD/MM/YYYY) i updated my osu, and then either the replay viewer nor firedigger's replayAnalyzer got to work. any help?

**Comment by FlavienROUX** [comment]
same for me

**Comment by thebetioplane** [comment]
Okay so I realize there is a problem, and the wiki says that there are changes to the osu!.db file format effective in version 20191106.

https://osu.ppy.sh/help/wiki/osu!_File_Formats/Db_(file_format)

I've decided that I **will** fix this (even though mentally I decided to not fix anything in this code base).
This has some implications: for one this project (as many people have found out) uses Microsoft XNA, which is obsolete -- I haven't even had an XNA environment set up in several years to compile the project even if I wanted to change something. That means I will be porting the codebase to OpenTK + an OpenGL based rendering system. This should have minimal effect visually but will at least allow me to compile the project again.

So expect soon an update that includes these three things:

(1) allows the new osu!.db

(2) removes XNA depency

(3) probably remove the updater and integrate checking for updates (if enabled) into the main binary itself. Having two programs, especially one that looks like trash upsets me.

**Comment by obrigadex** [comment]
> Okay so I realize there is a problem, and the wiki says that there are changes to the osu!.db file format effective in version 20191106.
> 
> https://osu.ppy.sh/help/wiki/osu!_File_Formats/Db_(file_format)
> 
> I've decided that I **will** fix this (even though mentally I decided to not fix anything in this code base).
> This has some implications: for one this project (as many people have found out) uses Microsoft XNA, which is obsolete -- I haven't even had an XNA environment set up in several years to compile the project even if I wanted to change something. That means I will be porting the codebase to OpenTK + an OpenGL based rendering system. This should have minimal effect visually but will at least allow me to compile the project again.
> 
> So expect soon an update that includes these three things:
> 
> (1) allows the new osu!.db
> 
> (2) removes XNA depency
> 
> (3) probably remove the updater and integrate checking for updates (if enabled) into the main binary itself. Having two programs, especially one that looks like trash upsets me.

i have no idea what that is. but im excited xd

**Comment by thebetioplane** [comment]
I've pushed out the first update with the changes that I've highlighted above, there may still be some missing features (that existed before)... one I already noticed is that flipping the cursor no longer works.
If you notice any other issues or have any questions post them here (or in a separate issue) and I'll try to take care of it the best I can.
I've barely done any testing and I'm especially concerned that CPU performance may be poor (or at least worse than the previous version).

**Comment by FlavienROUX** [comment]
Thanks for the update juste with HR maps my cursor do the right way but the map is in No Mod so my cursor don't follow the map

**Comment by thebetioplane** [comment]
Yes there was an issue with hardrock not flipping as well as the the manual "Y-axis flip" option not working. Today I fixed them both.

**Comment by FlavienROUX** [comment]
OsuReplayViewer forgot to display notes I think https://imgur.com/a/03vwHCu

**Comment by Naiedaos** [comment]
Had the same issue on my end watching this replay fwiw

**Comment by obrigadex** [comment]
> Had the same issue on my end watching this replay fwiw

that was already happening sometimes in the other replayViewer...

**Comment by thebetioplane** [comment]
Yes this is a bug that has existed since forever, it's never been fixed because I don't exactly know what causes it ... just that it only happens on sliders and it might have something to do with the "pixel length" parameter that is in the .osu file. It might be a while before this gets taken care of.

**Comment by thebetioplane** [comment]
Here we are six months later and I've fixed at least two bugs that prevent sliders from being rendered (at a minimum it fixes the beatmap that you provided a screen capture of). Let me know if you notice this breaking other sliders, I don't think it does though.

https://github.com/thebetioplane/OsuReplayViewer/commits/master

You can view full change log information on this page and then click the "..." for each commit to view the longer description.
